name: xdZoneEdit
version: 0.0.1
dependencies:
  angular: '0.9.8'
  browser: any
  shadow_dom: any
  google_oauth2_client: '>=0.3.4'
  google_dns_v1beta1_api: ">=0.4.0 <0.5.0"
  angular_dart_ui_bootstrap: ">=0.2.1 <0.3.0"
  sass: ">=0.3.0 <0.4.0"

transformers:
  - sass

